# secretScanningGitApp:
#   enabled: false
#   deploymentAnnotations:
#     secrets.infisical.com/auto-reload: "true"
#   image:
#     repository: infisical/staging_deployment_secret-scanning-git-app
    
frontend:
  enabled: true
  name: frontend
  podAnnotations: {}
  deploymentAnnotations:
    secrets.infisical.com/auto-reload: "true"
  replicaCount: 2
  image:
    repository: infisical/staging_deployment_frontend
    tag: "latest"
    pullPolicy: Always
  kubeSecretRef: managed-secret-frontend
  service:
    annotations: {}
    type: ClusterIP
    nodePort: ""

frontendEnvironmentVariables: null

backend:
  enabled: true
  name: backend
  podAnnotations: {}
  deploymentAnnotations:
    secrets.infisical.com/auto-reload: "true"
  replicaCount: 2
  image:
    repository: infisical/staging_deployment_backend
    tag: "latest"
    pullPolicy: Always
  kubeSecretRef: managed-backend-secret
  service:
    annotations: {}
    type: ClusterIP
    nodePort: ""
  resources:
    limits:
      memory: 300Mi

backendEnvironmentVariables: null

## Mongo DB persistence
mongodb:
  enabled: false
  persistence:
    enabled: false

## By default the backend will be connected to a Mongo instance within the cluster
## However, it is recommended to add a managed document DB connection string for production-use (DBaaS)
## Learn about connection string type here https://www.mongodb.com/docs/manual/reference/connection-string/
## e.g. "mongodb://<user>:<pass>@<host>:<port>/<database-name>"
mongodbConnection:
  externalMongoDBConnectionString: ""

ingress:
  enabled: true
  # annotations:
  #   kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/issuer: letsencrypt-nginx
  hostName: gamma.infisical.com ## <- Replace with your own domain
  frontend:
    path: /
    pathType: Prefix
  backend:
    path: /api
    pathType: Prefix
  tls:
    []
    # - secretName: letsencrypt-nginx
    #   hosts:
    #     - infisical.local

mailhog:
  enabled: false
