## @section Common parameters
##

## @param nameOverride Override release name
##
nameOverride: ""
## @param fullnameOverride Override release fullname
##
fullnameOverride: ""

## @section Infisical backend parameters
## Documentation : https://infisical.com/docs/self-hosting/deployments/kubernetes
##

infisical:
  ## @param backend.enabled Enable backend
  ##
  enabled: false
  ## @param backend.name Backend name
  ##
  name: infisical
  replicaCount: 2
  image:
    repository: infisical/infisical
    tag: "latest-postgres"
    pullPolicy: IfNotPresent

  deploymentAnnotations:
    secrets.infisical.com/auto-reload: "true"

  kubeSecretRef: "infisical-gamma-secrets"

ingress:
  ## @param ingress.enabled Enable ingress
  ##
  enabled: true
  ## @param ingress.ingressClassName Ingress class name
  ##
  ingressClassName: nginx
  ## @param ingress.nginx.enabled Ingress controller
  ##
  # nginx:
  #   enabled: true
  ## @param ingress.annotations Ingress annotations
  ##
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hostName: "gamma.infisical.com"
  tls:
    - secretName: letsencrypt-prod
      hosts:
        - gamma.infisical.com
