apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: infisical-api-secret-sample-push
spec:
  resyncInterval: 1m
  hostAPI: http://localhost:8080/api

  # Optional, defaults to replacement.
  updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

  # Optional, defaults to no deletion.
  deletionPolicy: Delete # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

  destination:
    projectId: "<project-id>"
    environmentSlug: dev
    secretsPath: /

  push:
    secret:
      secretName: push-secret-source-secret # Secret CRD
      secretNamespace: default

  # Only have one authentication method defined or you are likely to run into authentication issues.
  # Remove all except one authentication method.
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials # universal-auth-credentials
        secretNamespace: default # default
