name: Check Frontend Type and Lint check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "frontend/**"
      - "!frontend/README.md"
      - "!frontend/.*"
      - "frontend/.eslintrc.js"

jobs:
  check-fe-ts-lint:
    name: Check Frontend Type and Lint check
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: â˜ï¸ Checkout source
        uses: actions/checkout@v3
      - name: ğŸ”§ Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: ğŸ“¦ Install dependencies
        run: npm install
        working-directory: frontend
      - name: ğŸ—ï¸ Run Type check
        run: npm run type:check 
        working-directory: frontend
      - name: ğŸ—ï¸ Run Link check
        run: npm run lint:fix 
        working-directory: frontend
